[project]
name = "nephelaiio-plugins"
version = "0.0.1"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]
readme = "README.md"
requires-python = ">=3.11,<3.14"

[dependency-groups]
dev = [
  "pokerops-ansible-utils@git+https://github.com/pokerops/ansible-utils@master",
  "black>=26.3.1",
  "ruff>=0.15.13",
  "ty>=0.0.35",
  "pytest>=9.0.3",
  "basedpyright>=1.39.4",
]

[tool.ty.environment]
python = ".venv"

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "off"

[tool.pytest.ini_options]
pythonpath = ["plugins/filter", "plugins/test"]

[tool.ty.rules]
unresolved-attribute = "ignore"
