---
all:
  vars:
    inventory_global_id: molecule
    inventory_id: primary
  hosts:
    pri_first_level_a:
      ansible_host: 10.0.0.1
      alias: first_a
    pri_first_level_b:
      ansible_host: 10.0.0.2
      alias: first_b
    pri_second_level_a:
      ansible_host: 10.0.1.1
      alias: second_a
    pri_second_level_b:
      ansible_host: 10.0.1.2
      alias: second_b
    pri_third_level_a:
      ansible_host: 10.0.2.1
    pri_third_level_b:
      ansible_host: 10.0.2.2

select_levels:
  vars:
    group_id: primary_select_levels
  children:
    first_level:
    second_level:

first_level:
  hosts:
    pri_first_level_a:
    pri_first_level_b:

second_level:
  hosts:
    pri_second_level_a:
    pri_second_level_b:

third_level:
  hosts:
    pri_third_level_a:
    pri_third_level_b:

private_level:
  children:
    first_level:
    third_level:
