---
all:
  vars:
    inventory_global_id: molecule
    inventory_id: secondary
  hosts:
    snd_first_level_a:
      ansible_host: 10.0.0.1
      alias: first_a
      host_id: snd_first_level_a
    snd_first_level_b:
      ansible_host: 10.0.0.2
      alias: first_b
      host_id: snd_first_level_b
    snd_second_level_a:
      ansible_host: 10.0.1.1
      alias: second_a
    snd_second_level_b:
      ansible_host: 10.0.1.2
      alias: second_b
    snd_third_level_a:
      ansible_host: 10.0.2.1
    snd_third_level_b:
      ansible_host: 10.0.2.2

select_levels:
  vars:
    group_id: secondary_select_levels
  children:
    first_level:
    second_level:

first_level:
  hosts:
    snd_first_level_a:
    snd_first_level_b:

second_level:
  hosts:
    snd_second_level_a:
    snd_second_level_b:

third_level:
  hosts:
    snd_third_level_a:
    snd_third_level_b:
