---
name: test

on:
  pull_request:
    branches:
      - master

jobs:
  molecule:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - filter
          - composite
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Install role requirements
        run: make requirements

      - name: Run tests.
        run: make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
