---
name: test
on:
  pull_request:
    branches:
      - master
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Run python test
        uses: pokerops/ansible-utils@master
        with:
          run: just python-test
          cache: "false"

  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - filter
          - composite
    steps:
      - name: Run molecule test
        uses: pokerops/ansible-utils@master
        with:
          run: just --set MOLECULE_SCENARIO ${{ matrix.scenario }} test
          cache: "false"
